Repository industrieco/blockchain-bootcamp, pull requests merged in 2018-03, with the labels that each got.

#3 [documentation, optimisation, n/a] minor updates to dependencies and notes
  .circleci/config.yml
  CONTRIBUTING.md
  README.md
  course-notes/0-Preparation/README.md
  course-notes/1-Introduction/README.md
  package-lock.json
  package.json
Labels: documentation, enhancement

#4 [Documentation, Day-1] Added updated notes
  course-notes/1-Introduction/README.md
  course-notes/1-Introduction/contracts/HelloWorld.sol
  course-notes/1-Introduction/contracts/HelloWorldBytes.sol
  course-notes/1-Introduction/contracts/SayHello.sol
  course-notes/1-Introduction/images/proof-of-work.jpg
  course-notes/1-Introduction/images/the-state-tree.png
Labels: documentation

#7 [Feature] Added many functions
  contracts/BattleshipsV1.sol
Labels: feature

#5 Feature/play turn
  contracts/BattleshipsV1.sol
Labels: feature

#10 [Feature] Added the capabilty to place ships either horizontally or vertically
  contracts/Battleships.sol
  contracts/BattleshipsV1.sol
Labels: feature

#12 [Feature, Day-2] add notes from today and tests for tomorrow
  .circleci/config.yml
  .solcover.js
  README.md
  contracts/BattleshipsV1.sol
  course-notes/0-Preparation/README.md
  course-notes/2-Solidity/README.md
  package-lock.json
  package.json
  test/creation/BattleshipsV1.test.js
  test/dummy_test.js
  test/interaction/BattleshipsV1-AllShipsPlaced.test.js
  test/interaction/BattleshipsV1-PlaceShip.test.js
  test/interaction/BattleshipsV1-gameOver.test.js
  test/interaction/BattleshipsV1-startGame.test.js
  test/utils/checkShipsNotPlaced.js
  test/utils/zero.js
Labels: feature

#16 Feature/game over
  contracts/Battleships.sol
  contracts/BattleshipsV1.sol
  package-lock.json
  package.json
  test/creation/BattleshipsV1.test.js
Labels: bug, feature

#24 [Feature, Day-5] added ropsten deployment
  README.md
  migrations/2_deploy_it.js
  package-lock.json
  package.json
  truffle.js
Labels: feature
